package testgen_test

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/khei4/ccffer/model"
	"github.com/khei4/ccffer/testgen"
)

func TestGenTests(t *testing.T) {
	appint := &model.App{TypeInstances: []model.Type{"int"}, Args: []model.Val{"0"}}
	appstring := &model.App{TypeInstances: []model.Type{"string"}, Args: []model.Val{`""`}}
	gf := model.GenFunc{FName: "F", Apps: []*model.App{appint, appstring}}
	td := model.TemplData{
		PkgPath:  "main",
		PkgName:  "main",
		GenFuncs: []*model.GenFunc{&gf},
	}

	var testsrc bytes.Buffer
	testgen.TestTmpl.Execute(&testsrc, td)
	expectedraw := `// Code generated by ccffer; DO NOT EDIT.
	
package main_test
import (
        "testing"
        "main"
)
func TestF(t *testing.T) {
	main.F[int,](0,)
	main.F[string,]("",)
	
}

`

	expected, _ := testgen.FormatAndImport([]byte(expectedraw))
	if got, err := testgen.GenTests(&td); got != expected || err != nil {
		fmt.Print(got)
		t.Fatalf("%v\n is not \n%v", got, expected)
	}

}
